### ISSUE TITLE
Super Monkeys and Dart Monkeys are not loading their crosspaths

### ISSUE THREAD

**Issue by Youhadabadday** [doombubbles/ultimate-crosspathing#96]
# Installation Error

### Mod Version

V1.3.6

### Mod Helper Version
V3.1.4

### Description
Everytime I load up the Ultimate Crosspath mod with the new Bloons update, I get a message that says "2 towers failed to Ultimately Crosspath." Investigation into the console reveals that errors popped up when loading the Dart Monkey and Super Monkey.

### Other Mods

![image](https://user-images.githubusercontent.com/55116935/219469310-0563d3a9-7c5d-4567-b039-ae8889caa6c7.png)

### Logs

[Latest.log](https://github.com/doombubbles/ultimate-crosspathing/files/10759982/Latest.log)

**Comment by CloneMike** [comment]
Im trying to load into btd 6 with mods and this happens to me to. From looking at the error, it seems like it might have something to do with the fact both supermonkey and dartmonkey can crit. The image bellow is what i found. Now, im no actual coder so i have no idea if the issue is even related to crits but just pointing that out. but all the other towers work though. but sniper might not also work considering with mega knowledge he can crit. i havnt tested that yet though. 
![image](https://user-images.githubusercontent.com/125628961/219546218-ea1cd080-0669-40fb-975d-3d735870d31b.png)

**Comment by Wardifger** [comment]
Same thing here, crosspathing doesn't work on the dartmonkey and the supermonkey

**Comment by Youhadabadday** [comment]
Closing this. Fixed with recent update.
